
omniMode: false

use_wbc: false


horizon: 15
constraint_num: 16
iteration_between_mpc: 20

q1: 1
q2: 0.25
q3: 20
q4: 2
q5: 2
q6: 30
q7: 0
q8: 0
q9: 0.5
q10: 0.2
q11: 0.4
q12: 0.2

r1: 1e-6
r2: 1e-6
r3: 1e-6
r4: 1e-6
r5: 1e-6
r6: 1e-6

kp_cartesian_x: 2000
kp_cartesian_y: 800
kp_cartesian_z: 1200
kp_cartesian_r: 2000
kp_cartesian_p: 800
kp_cartesian_y: 1200

kd_cartesian_x: 5
kd_cartesian_y: 5
kd_cartesian_z: 1
kd_cartesian_r: 5
kd_cartesian_p: 5
kd_cartesian_y: 1

body_height_stand: 0.8
body_height_motion: 0.8

swing_height_walking: 0.1

