
kp_joint_leg_1: 3
kp_joint_leg_2: 3
kp_joint_leg_3: 3
kp_joint_leg_4: 3
kp_joint_leg_5: 3
kp_joint_torso: 3
kp_joint_arm_1: 3
kp_joint_arm_2: 3
kp_joint_arm_3: 3
kp_joint_arm_4: 3

kd_joint_leg_1: 0.2
kd_joint_leg_2: 0.2
kd_joint_leg_3: 0.2
kd_joint_leg_4: 0.2
kd_joint_leg_5: 0.2
kd_joint_torso: 0.2
kd_joint_arm_1: 0.2
kd_joint_arm_2: 0.2
kd_joint_arm_3: 0.2
kd_joint_arm_4: 0.2


kp_body_ori_x: 100
kp_body_ori_y: 100
kp_body_ori_z: 100

kd_body_ori_x: 10
kd_body_ori_y: 10
kd_body_ori_z: 10

kp_body_pos_x: 100
kp_body_pos_y: 100
kp_body_pos_z: 100

kd_body_pos_x: 10
kd_body_pos_y: 10
kd_body_pos_z: 10

kp_foot_x: 200
kp_foot_y: 200
kp_foot_z: 200
kp_foot_roll: 200
kp_foot_pitch: 200
kp_foot_yaw: 200
kp_hand_x: 0
kp_hand_y: 0
kp_hand_z: 0
kp_hand_roll: 0
kp_hand_pitch: 0
kp_hand_yaw: 0

kd_foot_x: 20
kd_foot_y: 20
kd_foot_z: 20
kd_foot_roll: 20
kd_foot_pitch: 20
kd_foot_yaw: 20
kd_hand_x: 0
kd_hand_y: 0
kd_hand_z: 0
kd_hand_roll: 0
kd_hand_pitch: 0
kd_hand_yaw: 0

weight_floating: 10
weight_reaction_force: 1

