
# weights
Q:
  q1: 1
  q2: 1
  q3: 0.1
  q4: 0.1
Qn:
  q1: 500
  q2: 500
  q3: 100
  q4: 100
R:
  r1: 0.01

# dynamics parameters
m_cart: 1
m_pole: 0.1
l: 1

# init
initial_state:
  pos: 0
  theta: -3.1416
  vel: 0
  omega: 0

# iLQR cal
dt: 0.005
step: 0.01
Tfinal: 0.5